base_images:
  base-rhel9:
    name: "4.17"
    namespace: ocp
    tag: base-rhel9
  cli-operator-sdk:
    name: cli-operator-sdk
    namespace: ocp
    tag: v1.30.0
  ocp-golang-builder:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.22-openshift-4.17
binary_build_commands: make build --warn-undefined-variables
build_root:
  from_repository: true
images:
- dockerfile_path: images/ci/Dockerfile
  from: base-rhel9
  inputs:
    ocp-golang-builder:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17
  to: cert-manager-operator
- dockerfile_path: images/ci/operand.Dockerfile
  from: base-rhel9
  inputs:
    ocp-golang-builder:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17
  to: cert-manager
operator:
  bundles:
  - as: cert-manager-operator-bundle
    dockerfile_path: bundle.Dockerfile
  substitutions:
  - pullspec: openshift.io/cert-manager-operator:latest
    with: pipeline:cert-manager-operator
  - pullspec: quay.io/jetstack/cert-manager-controller:v1.15.5
    with: pipeline:cert-manager
  - pullspec: quay.io/jetstack/cert-manager-webhook:v1.15.5
    with: pipeline:cert-manager
  - pullspec: quay.io/jetstack/cert-manager-cainjector:v1.15.5
    with: pipeline:cert-manager
releases:
  initial:
    integration:
      name: "4.17"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.17"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: verify
  commands: |
    make verify -k --warn-undefined-variables
  container:
    from: src
- as: verify-deps
  commands: |
    make verify-deps -k --warn-undefined-variables
  container:
    from: src
- as: unit
  commands: |
    make test --warn-undefined-variables
  container:
    from: src
- as: fips-image-scan-operator
  steps:
    dependencies:
      SCAN_IMAGE: cert-manager-operator
    test:
    - ref: fips-check-image-scan
- as: fips-image-scan-cert-manager
  steps:
    dependencies:
      SCAN_IMAGE: cert-manager
    test:
    - ref: fips-check-image-scan
- as: e2e-operator
  steps:
    cluster_profile: aws
    dependencies:
      OO_BUNDLE: cert-manager-operator-bundle
    env:
      FIPS_ENABLED: "true"
      OO_INSTALL_MODE: AllNamespaces
      OO_INSTALL_NAMESPACE: cert-manager-operator
      OO_SECURITY_CONTEXT: restricted
    test:
    - as: install
      cli: latest
      commands: |
        oc -n cert-manager-operator rollout status deployment cert-manager-operator-controller-manager
      from: src
      resources:
        requests:
          cpu: 100m
    - ref: fips-check-fips-or-die
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: optional-operators-ci-operator-sdk-aws
- as: e2e-operator-upgrade
  steps:
    cluster_profile: aws
    test:
    - as: install
      cli: latest
      commands: |
        export REGISTRY_AUTH_FILE=/tmp/import-secret/.dockerconfigjson
        export DOCKER_CONFIG=/tmp/.docker
        mkdir -p $DOCKER_CONFIG
        cp $REGISTRY_AUTH_FILE $DOCKER_CONFIG/config.json
        cd /tmp
        oc create namespace cert-manager-operator
        operator-sdk run bundle --security-context-config restricted -n cert-manager-operator registry.redhat.io/cert-manager/cert-manager-operator-bundle:v1.14.1
        oc wait --timeout=10m --for condition=Available -n cert-manager-operator deployment cert-manager-operator-controller-manager
        oc get deployment -n cert-manager
      credentials:
      - mount_path: /tmp/pull-secret
        name: registry-pull-credentials
        namespace: test-credentials
      - mount_path: /tmp/import-secret
        name: ci-pull-credentials
        namespace: test-credentials
      from: cli-operator-sdk
      resources:
        requests:
          cpu: 100m
    - as: upgrade
      cli: latest
      commands: |
        operator-sdk run bundle-upgrade --security-context-config restricted -n cert-manager-operator "$OO_BUNDLE"
        oc wait --timeout=10m --for condition=Available -n cert-manager-operator deployment cert-manager-operator-controller-manager
        oc get deployment -n cert-manager
      dependencies:
      - env: OO_BUNDLE
        name: cert-manager-operator-bundle
      from: cli-operator-sdk
      resources:
        requests:
          cpu: 100m
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: cert-manager-operator
